ok

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -65,14 +65,21 @@ jobs:
       
       - name: Setup Lime
         run: |
-          haxelib run lime setup android
           haxelib run lime config ANDROID_SDK $ANDROID_HOME
           haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
           haxelib run lime config JAVA_HOME $JAVA_HOME_21_X64
           haxelib run lime config ANDROID_SETUP true
           
+      - name: Rebuild Android Lime so
+        run: |
+          haxelib run lime rebuild android -release
+          if [ ! -f .haxelib/lime/git/ndll/Android/liblime-64.so ]; then
+            echo "ERROR: Missing Liblime 64 so"
+            exit 1
+          fi
+      
       - name: Compile
-        run: haxelib run lime build android -ONLY_ARM64
+        run: haxelib run lime build android -ONLY_ARM64 -D DLC
       
       - name: Publish Artifact
         uses: actions/upload-artifact@main
